# Generated by Django 4.2.18 on 2025-01-31 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='consultingassignment',
            options={'ordering': ['-created_on']},
        ),
    ]
